### ISSUE TITLE
Source and SMOTE

### ISSUE THREAD

**Issue by turkalpmd** [uraninjo/DiseaseDetection#1]
hocam datasetin kaynağı nedir, bir de medikal verilerde SMOTE özellikle de Tomeklin ile fena olmuyor

**Comment by uraninjo** [comment]
Smote ve Tomek Links'e bakıp uygulayacağım. Teşekkür ederim...

https://www.kaggle.com/datasets/tourist55/alzheimers-dataset-4-class-of-images
https://www.kaggle.com/datasets/debasisdotcom/parkinson-disease-detection
https://www.kaggle.com/datasets/navoneel/brain-mri-images-for-brain-tumor-detection
